version: '3.8'
services:
  hello-world:
    image: hello-world
  web:
    image: docker-registry.amilabs.net/everexdev/hello-world:latest
    ports:
      - "${PORT}:3000"
    environment:
      - TEST_ENV